apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary
  namespace: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-primary
  template:
    metadata:
      labels:
        app: postgres-primary
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: postgres
          image: 'postgres:13'
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - configMapRef:
              name: postgres-replication-config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
